--- #YAML:1.0
name:                Tk-Date
version:             0.43
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Tk:                            402.002
    Tk::FireButton:                0.05
    Tk::NumEntry:                  1.08
    Tk::NumEntryPlain:             0.02
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
